spring:
  application:
    name: cabin-IM
server:
  port: 8081
  http:
    enabled: false
  netty:
    worker-count: 4

---
#admin监控
spring:
  boot:
    admin:
      client:
        url: http://${admin_host:127.0.0.1}:9001
        username: user
        password: zhangyang
# 开启监控所有项
management:
  endpoints:
    web:
      exposure:
        include: "*"
#spring:
#  security:
#    user:
#      name: admin
#      password: admin

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:3306/cabin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${mysql_username}
    password: ${mysql_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
