spring:
  banner:
    location: banner/banner.txt
  application:
    name: cabin-monitor
server:
  port: 9003

influxdb:
  url: ${influxdb_url}
  token: ${influxdb_token}
  bucket: ${influxdb_bucket}
  org: ${influxdb_org}
notice:
  email: ${notice_email}
---
# mq
spring:
  rabbitmq:
    host: ${host}
    port: 5672
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    listener:
      direct:
        acknowledge-mode: manual

---
# 邮箱配置
spring:
  mail:
    host: smtp.qq.com #邮件服务器地址
    #端口号 smtp 25 465 pop3 110 995 imap 143 993
    # 阿里云默认封禁25,建议465
    # https://help.aliyun.com/document_detail/56130.html
    port: 465
    protocol: smtp
    username: ${mail_qq_username}
    password: ${mail_qq_password}
    default-encoding: UTF-8 #默认编码格式
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false