code:
  host: ${host}
spring:
  application:
    name: cabin-app
server:
  port: 8080

logging:
  config:
    classpath: logback-spring.xml
  file:
    path: ${cabin_app_logs}

---
#admin监控
spring:
  boot:
    admin:
      client:
        url: http://${admin_host:127.0.0.1}:9001
        username: user
        password: zhangyang
# 开启监控所有项
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  # 配置时区
  jackson:
    time-zone: GMT+8
  datasource:
    dynamic:
      # 主数据源
      primary: app
      datasource:
        # 数据源1
        app:
          #          driver-class-name: oracle.jdbc.OracleDriver
          #          url: jdbc:oracle:thin:@10.57.30.95:1525:WOKDSD
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${host}:3306/cabin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: ${mysql_username}
          password: ${mysql_password}
        # 数据源2
        information:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${host}:3306/information_schema?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: ${mysql_username}
          password: ${mysql_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
#      # druid 全局配置
#      druid:
#        initial-size: 5
#        min-idle: 5
#        max-active: 20
#        max-wait: 60000
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 30000
#        validation-query: SELECT 1 FROM DUAL
#        test-while-idle: true
#        test-on-borrow: true
#        test-on-return: false
#
---
spring:
  data:
    redis:
      host: ${host}
      password: ${redis_password}





mybatis-plus:
  # mapper文件路径
  mapper-locations: classpath:mapper/*/*.xml
  # SQL日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.cabin.entity

---
influxdb:
  url: http://127.0.0.1:8086
  username: root         #用户
  password: 123          #密码
  database: test         #库
#spring:
#  influx:
#    url: http://120.55.99.46/:8086
#    user: user
#    password: zhangyang
#    mapper-location: com.cabin.mapper.influxDB

---
# 通知
# 钉钉webhook
dingding:
  access_token: ${dingding_api_inform_access_token}
  secret: ${dingding_api_inform_secret}


dingdingalarm:
  access_token: ${dingding_alarm_access_token}
  secret: ${dingding_alarm_secret}

# 邮箱配置
spring:
  mail:
    host: smtp.qq.com #邮件服务器地址
    #端口号 smtp 25 465 pop3 110 995 imap 143 993
    # 阿里云默认封禁25,建议465
    # https://help.aliyun.com/document_detail/56130.html
    port: 465
    protocol: smtp
    username: ${mail_qq_username}
    password: ${mail_qq_password}
    default-encoding: UTF-8 #默认编码格式
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  # mq
  rabbitmq:
    host: ${host}
    port: 5672
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    listener:
      direct:
        acknowledge-mode: manual