code:
  host: ${host}
server:
  port: 8080
#admin监控
spring:
  boot:
    admin:
      client:
        url: http://localhost:9001/admin
# 开启监控所有项
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  # 配置时区
  jackson:
    time-zone: GMT+8
  application:
    name: cabin
  datasource:
    dynamic:
      # 主数据源
      primary: app
      datasource:
        # 数据源1
        app:
          #          driver-class-name: oracle.jdbc.OracleDriver
          #          url: jdbc:oracle:thin:@10.57.30.95:1525:WOKDSD
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${host}:3306/cabin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: ${mysql_username}
          password: ${mysql_password}
        # 数据源2
        information:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${host}:3306/information_schema?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: ${mysql_username}
          password: ${mysql_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
#      # druid 全局配置
#      druid:
#        initial-size: 5
#        min-idle: 5
#        max-active: 20
#        max-wait: 60000
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 30000
#        validation-query: SELECT 1 FROM DUAL
#        test-while-idle: true
#        test-on-borrow: true
#        test-on-return: false
#
---
spring:
  data:
    redis:
      host: ${host}
      password: ${redis_password}
logging:
  config:
    classpath: logback-spring.xml
  file:
    path: F:\CODE_mid\MyCode\Individual-cabin\log


mybatis-plus:
  # mapper文件路径
  mapper-locations: classpath:mapper/*/*.xml
  # SQL日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.cabin.entity

---
influxdb:
  url: http://127.0.0.1:8086
  username: root         #用户
  password: 123          #密码
  database: test         #库
#spring:
#  influx:
#    url: http://120.55.99.46/:8086
#    user: user
#    password: zhangyang
#    mapper-location: com.cabin.mapper.influxDB