server:
  port: 9090
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: app           # 路由的唯一标识
#          uri: http://localhost:8080  # 如果断言成功，将要转发去的地址
#          order: 0                    # 优先级，越小优先级越高
#          predicates:                 # 断言，满足所有断言，才会进行转发
#            - Path=/app/**        # 注意：这是使用= 不是：
#          filters:
spring:
  data:
    redis:
      host: ${host}
      port: 6379
      password: ${redis_password}
#            - StripPrefix=1 # #转发请求时去掉1级前缀，去掉端口后的第一个节点，这里是client