server:
  port: 9001
  servlet:
    context-path: /admin
# RocketMQ Consumer 配置
monitor:
  rocketmq:
    namesrvAddr: ${rocketmq.namesrvAddr:localhost:9876}
    brokerAddr: ${rocketmq.brokerAddr:localhost:10911}
    defaultTopicName: ${rocketmq.defaultTopicName:localhost}
    consumerGROUP: ${rocketmq.consumerGROUP:testGroup}


