server:
  port: 9002
---
# 数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:3306/cabin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${mysql_username}
    password: ${mysql_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${host}
      password: ${redis_password}
---
# mq
spring:
  rabbitmq:
    host: ${host}
    port: 5672
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    listener:
      direct:
        acknowledge-mode: manual

---
# 邮箱配置
spring:
  mail:
    host: smtp.qq.com #邮件服务器地址
    #端口号 smtp 25 465 pop3 110 995 imap 143 993
    # 阿里云默认封禁25,建议465
    # https://help.aliyun.com/document_detail/56130.html
    port: 465
    protocol: smtp
    username: ${mail_qq_username}
    password: ${mail_qq_password}
    default-encoding: UTF-8 #默认编码格式
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
feishu:
  client:
    code_url_prefix: https://passport.feishu.cn/suite/passport/oauth/authorize
    token_url_prefix: https://passport.feishu.cn/suite/passport/oauth/token
    user_url_prefix: https://passport.feishu.cn/suite/passport/oauth/userinfo
    client_id: ${client_id}
    client_secret: ${client_secret}
    redirect_url_get_token: ${redirect_url_get_token}